[[plugins]]
repo = "Shougo/denite.nvim"
on_cmd = "Denite"
hook_source = """
source ~/.config/vim/plugins/denite.vim
"""

# [[plugins]]
# repo = "Shougo/deoplete.nvim"
# depends = "context_filetype.vim"
# on_event = "InsertEnter"
# hook_source = """
# source ~/.config/vim/plugins/deoplete.vim
# call deoplete#enable()
# """
